services:
  frontend:
    build: frontend/
    volumes:
      - ./frontend:/app/
    network_mode: host
    tty: true
    command: bash
  backend:
    build: .
    volumes:
      - ./rewild:/app/
    network_mode: host