# Generated by Django 5.1.5 on 2025-02-01 11:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='missiontype',
            name='valid_date_end',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 1, 11, 2, 46, 960490, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='missiontype',
            name='valid_date_start',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 1, 11, 2, 52, 744419, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
