# Generated by Django 5.1.5 on 2025-02-01 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_missiontype_valid_date_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missioninstance',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
