# Generated by Django 5.1.5 on 2025-02-01 13:33

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_missioninstance_completed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='boundary',
            field=django.contrib.gis.db.models.fields.PolygonField(default='POLYGON(( 10 10, 10 20, 20 20, 20 15, 10 10))', srid=4326),
        ),
    ]
