# Generated by Django 5.1.5 on 2025-02-01 15:42

import datetime
import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_location_boundary'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoneMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gps_coordinates', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, spatial_index=False, srid=4326)),
                ('completion_date', models.DateTimeField(default=datetime.datetime.now)),
                ('image', models.ImageField(upload_to='')),
                ('mission_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.missioninstance')),
            ],
        ),
        migrations.DeleteModel(
            name='DoneIntervention',
        ),
    ]
