# Generated by Django 5.1.5 on 2025-02-01 20:43

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_donemission_delete_doneintervention'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wildlifesighting',
            name='location',
        ),
        migrations.AddField(
            model_name='wildlifesighting',
            name='spot_location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, spatial_index=False, srid=4326),
        ),
    ]
